development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://eekzgpgvactwdn:68dc11a19a6edc185a47ab2378f69d6aa35082132996bab5cf8aee2c44dd93b1@ec2-54-163-246-5.compute-1.amazonaws.com:5432/def59g1bk2a6no
  channel_prefix: FirstApp_production
